name: PR Checks

on: [pull_request]

jobs:
    pr-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              with:
                  types: feat,fix,chore,docs,refactor,test,ci,perf,build

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - run: pnpm install --frozen-lockfile
            - run: pnpm run lint
            - run: pnpm run check
