name: Release

on:
    push:
        branches: [main]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'
                  registry-url: 'https://registry.npmjs.org'
            - run: pnpm install --frozen-lockfile
            - run: pnpm run build
            - run: pnpm changeset publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
